[font]
size = 12 

[font.normal]
family = "Fira Code"

[window]
opacity = 0.8
decorations="None"

[window.padding]
x = 10
y = 10

[cursor.style]
shape = "Beam"
blinking = "Always"

[mouse]
hide_when_typing = true
